const API_URL = "http://localhost:3000/school/student";
const ADMIN_COOKIE = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MmZmZDFlMDJmNmQ4ODQ5ZjUxNzVhOCIsInJvbGUiOiJhZG1pbiIsImZpcnN0TmFtZSI6Ik5hd3JhcyIsImxhc3ROYW1lIjoiQWxraHJpc3NhdCIsImVtYWlsIjoibmF3cmFzYWxraHJpc3NhdEBnbWFpbC5jb20iLCJpYXQiOjE3Njc4NzYwNDYsImV4cCI6MTc2Nzg3OTY0Nn0.uimdLWWxQDcgFdcN5C-1biDZhrvfAD08YL77JqRbAGI";

const CLASS_1 = "695d4f84baf1d4e13e9a9992";
const CLASS_2 = "695d7234037e38b408f5d19c";
const CLASS_3 = "695d7abac2d24c8df11a313e";

const students = [
  // ===== CLASS 1 =====
  {
    name: "Ahmad Khaled",
    nationalId: "100245678901",
    dateOfBirth: "2006-03-12",
    gender: "male",
    currentClass: CLASS_1,
    parentName: "Khaled Ahmad",
    parentPhone: "0791234561",
    parentEmail: "ahmad.khaled@Scholaris.edu.jo",
    address: "Amman, Khalda, Wasfi Al-Tal Street, Building 12",
  },
  {
    name: "Mohammad Saleh",
    nationalId: "100245678902",
    dateOfBirth: "2005-11-05",
    gender: "male",
    currentClass: CLASS_1,
    parentName: "Saleh Mohammad",
    parentPhone: "0791234562",
    parentEmail: "mohammad.saleh@Scholaris.edu.jo",
    address: "Amman, Tlaa Al-Ali, Yajouz Road, Building 5",
  },
  {
    name: "Ali Hassan",
    nationalId: "100245678903",
    dateOfBirth: "2006-01-22",
    gender: "male",
    currentClass: CLASS_1,
    parentName: "Hassan Ali",
    parentPhone: "0791234563",
    parentEmail: "ali.hassan@Scholaris.edu.jo",
    address: "Amman, Jubaiha, University Street, Building 18",
  },
  {
    name: "Omar Youssef",
    nationalId: "100245678904",
    dateOfBirth: "2006-06-14",
    gender: "male",
    currentClass: CLASS_1,
    parentName: "Youssef Omar",
    parentPhone: "0791234564",
    parentEmail: "omar.youssef@Scholaris.edu.jo",
    address: "Amman, Sweifieh, Paris Street, Building 22",
  },
  {
    name: "Yazan Mahmoud",
    nationalId: "100245678905",
    dateOfBirth: "2005-09-02",
    gender: "male",
    currentClass: CLASS_1,
    parentName: "Mahmoud Yazan",
    parentPhone: "0791234565",
    parentEmail: "yazan.mahmoud@Scholaris.edu.jo",
    address: "Amman, Abdoun, Zahran Street, Building 9",
  },
  {
    name: "Khalil Ibrahim",
    nationalId: "100245678906",
    dateOfBirth: "2006-02-18",
    gender: "male",
    currentClass: CLASS_1,
    parentName: "Ibrahim Khalil",
    parentPhone: "0791234566",
    parentEmail: "khalil.ibrahim@Scholaris.edu.jo",
    address: "Amman, Shmeisani, Abdul Hameed Shoman Street, Building 14",
  },
  {
    name: "Fadi Nasser",
    nationalId: "100245678907",
    dateOfBirth: "2005-12-25",
    gender: "male",
    currentClass: CLASS_1,
    parentName: "Nasser Fadi",
    parentPhone: "0791234567",
    parentEmail: "fadi.nasser@Scholaris.edu.jo",
    address: "Amman, Marj Al-Hamam, Prince Rashid Street, Building 7",
  },
  {
    name: "Anas Tareq",
    nationalId: "100245678908",
    dateOfBirth: "2006-07-08",
    gender: "male",
    currentClass: CLASS_1,
    parentName: "Tareq Anas",
    parentPhone: "0791234568",
    parentEmail: "anas.tareq@Scholaris.edu.jo",
    address: "Amman, Tabarbour, Army Street, Building 31",
  },

  // ===== CLASS 2 =====
  {
    name: "Bilal Samir",
    nationalId: "100245678909",
    dateOfBirth: "2005-04-10",
    gender: "male",
    currentClass: CLASS_2,
    parentName: "Samir Bilal",
    parentPhone: "0791234569",
    parentEmail: "bilal.samir@Scholaris.edu.jo",
    address: "Amman, Al-Rabieh, Mecca Street, Building 16",
  },
  {
    name: "Hamza Rami",
    nationalId: "100245678910",
    dateOfBirth: "2006-10-01",
    gender: "male",
    currentClass: CLASS_2,
    parentName: "Rami Hamza",
    parentPhone: "0791234570",
    parentEmail: "hamza.rami@Scholaris.edu.jo",
    address: "Amman, Jabal Al-Hussein, King Abdullah Street, Building 4",
  },
  {
    name: "Laith Adel",
    nationalId: "100245678911",
    dateOfBirth: "2005-08-19",
    gender: "male",
    currentClass: CLASS_2,
    parentName: "Adel Laith",
    parentPhone: "0791234571",
    parentEmail: "laith.adel@Scholaris.edu.jo",
    address: "Amman, Jabal Amman, Rainbow Street, Building 11",
  },
  {
    name: "Qais Munir",
    nationalId: "100245678912",
    dateOfBirth: "2006-11-27",
    gender: "male",
    currentClass: CLASS_2,
    parentName: "Munir Qais",
    parentPhone: "0791234572",
    parentEmail: "qais.munir@Scholaris.edu.jo",
    address: "Amman, Um Uthaina, Al-Kindi Street, Building 6",
  },
  {
    name: "Saif Ahmad",
    nationalId: "100245678913",
    dateOfBirth: "2005-01-15",
    gender: "male",
    currentClass: CLASS_2,
    parentName: "Ahmad Saif",
    parentPhone: "0791234573",
    parentEmail: "saif.ahmad@Scholaris.edu.jo",
    address: "Zarqa, New Zarqa, Al-Jaish Street, Building 19",
  },
  {
    name: "Zaid Fawzi",
    nationalId: "100245678914",
    dateOfBirth: "2006-05-03",
    gender: "male",
    currentClass: CLASS_2,
    parentName: "Fawzi Zaid",
    parentPhone: "0791234574",
    parentEmail: "zaid.fawzi@Scholaris.edu.jo",
    address: "Zarqa, Prince Mohammad Street, Building 27",
  },
  {
    name: "Tamer Nabil",
    nationalId: "100245678915",
    dateOfBirth: "2005-07-21",
    gender: "male",
    currentClass: CLASS_2,
    parentName: "Nabil Tamer",
    parentPhone: "0791234575",
    parentEmail: "tamer.nabil@Scholaris.edu.jo",
    address: "Irbid, University District, Al-Hashmi Street, Building 8",
  },
  {
    name: "Rakan Suleiman",
    nationalId: "100245678916",
    dateOfBirth: "2006-09-09",
    gender: "male",
    currentClass: CLASS_2,
    parentName: "Suleiman Rakan",
    parentPhone: "0791234576",
    parentEmail: "rakan.suleiman@Scholaris.edu.jo",
    address: "Irbid, Al-Hayy Al-Sharqi, Building 15",
  },

  // ===== CLASS 3 =====
  {
    name: "Moath Jamal",
    nationalId: "100245678917",
    dateOfBirth: "2005-02-06",
    gender: "male",
    currentClass: CLASS_3,
    parentName: "Jamal Moath",
    parentPhone: "0791234577",
    parentEmail: "moath.jamal@Scholaris.edu.jo",
    address: "Salt, Al-Salt Al-Jadida, Building 3",
  },
  {
    name: "Hazem Ayman",
    nationalId: "100245678918",
    dateOfBirth: "2006-04-30",
    gender: "male",
    currentClass: CLASS_3,
    parentName: "Ayman Hazem",
    parentPhone: "0791234578",
    parentEmail: "hazem.ayman@Scholaris.edu.jo",
    address: "Madaba, Downtown, King Talal Street, Building 21",
  },
  {
    name: "Iyad Bassam",
    nationalId: "100245678919",
    dateOfBirth: "2005-06-17",
    gender: "male",
    currentClass: CLASS_3,
    parentName: "Bassam Iyad",
    parentPhone: "0791234579",
    parentEmail: "iyad.bassam@Scholaris.edu.jo",
    address: "Aqaba, Al-Shalala, Al-Hammamat Street, Building 10",
  },
  {
    name: "Sami Hani",
    nationalId: "100245678920",
    dateOfBirth: "2006-08-12",
    gender: "male",
    currentClass: CLASS_3,
    parentName: "Hani Sami",
    parentPhone: "0791234580",
    parentEmail: "sami.hani@Scholaris.edu.jo",
    address: "Aqaba, Al-Rimal District, Building 25",
  },
  {
    name: "Murad Firas",
    nationalId: "100245678921",
    dateOfBirth: "2005-10-28",
    gender: "male",
    currentClass: CLASS_3,
    parentName: "Firas Murad",
    parentPhone: "0791234581",
    parentEmail: "murad.firas@Scholaris.edu.jo",
    address: "Jerash, Downtown, Al-Hussein Street, Building 13",
  },
  {
    name: "Ayman Zaki",
    nationalId: "100245678922",
    dateOfBirth: "2006-12-04",
    gender: "male",
    currentClass: CLASS_3,
    parentName: "Zaki Ayman",
    parentPhone: "0791234582",
    parentEmail: "ayman.zaki@Scholaris.edu.jo",
    address: "Mafraq, King Hussein Street, Building 17",
  },
  {
    name: "Nidal Kareem",
    nationalId: "100245678923",
    dateOfBirth: "2005-03-19",
    gender: "male",
    currentClass: CLASS_3,
    parentName: "Kareem Nidal",
    parentPhone: "0791234583",
    parentEmail: "nidal.kareem@Scholaris.edu.jo",
    address: "Karak, Al-Qasr District, Building 20",
  },
  {
    name: "Rami Waleed",
    nationalId: "100245678924",
    dateOfBirth: "2006-01-11",
    gender: "male",
    currentClass: CLASS_3,
    parentName: "Waleed Rami",
    parentPhone: "0791234584",
    parentEmail: "rami.waleed@Scholaris.edu.jo",
    address: "Tafilah, Al-Eis District, Building 2",
  },
];

async function seedStudents() {
  for (const student of students) {
    try {
      const res = await fetch(API_URL, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Cookie: ADMIN_COOKIE,
        },
        body: JSON.stringify(student),
      });

      if (!res.ok) {
        const error = await res.text();
        throw new Error(error);
      }

      console.log(`✅ Created: ${student.name}`);
    } catch (err) {
      console.error(`❌ Failed: ${student.name}`, err.message);
    }
  }
}

seedStudents();
